// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBT-6vLktgxp9TvaFf-gRXl8ymZBA0XE',
    appId: '1:821545363363:web:e64d7c4b4f04c1af269c16',
    messagingSenderId: '821545363363',
    projectId: 'restaurant-app-22435',
    authDomain: 'restaurant-app-22435.firebaseapp.com',
    storageBucket: 'restaurant-app-22435.firebasestorage.app',
    measurementId: 'G-LRDP53M30R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREjyWDU-dZC-67f6Gifxdiuc6P3IrCj8',
    appId: '1:821545363363:android:27c2ae295636513e269c16',
    messagingSenderId: '821545363363',
    projectId: 'restaurant-app-22435',
    storageBucket: 'restaurant-app-22435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lI9ysGOnJN4T9ATCCO9fJS6ZuY7runs',
    appId: '1:821545363363:ios:c726188e238313a0269c16',
    messagingSenderId: '821545363363',
    projectId: 'restaurant-app-22435',
    storageBucket: 'restaurant-app-22435.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0lI9ysGOnJN4T9ATCCO9fJS6ZuY7runs',
    appId: '1:821545363363:ios:c726188e238313a0269c16',
    messagingSenderId: '821545363363',
    projectId: 'restaurant-app-22435',
    storageBucket: 'restaurant-app-22435.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFBT-6vLktgxp9TvaFf-gRXl8ymZBA0XE',
    appId: '1:821545363363:web:7c9544dec9637d25269c16',
    messagingSenderId: '821545363363',
    projectId: 'restaurant-app-22435',
    authDomain: 'restaurant-app-22435.firebaseapp.com',
    storageBucket: 'restaurant-app-22435.firebasestorage.app',
    measurementId: 'G-Z36F2335LC',
  );
}
